### ISSUE TITLE
Switching parameter from constant to witness breaks program

### ISSUE THREAD

**Issue by sanchopansa** [akosba/xjsnark#10]
I have the following program, which does (incomplete) ECDSA signature verification over the [baby_jubjub](https://github.com/barryWhiteHat/baby_jubjub) curve:
```java
Program ECDSA_Verification { 
 
  //  ECDSA verification using baby_jubjub curve 
   
  // Generator point 
  public F_q b_x = F_q("17777552123799933955779906779655732241715742912184938656739573121738514868268"); 
  public F_q b_y = F_q("2626589144620713026669568689430873010625803728049924121243784502389097019475"); 
   
  // Public key coordinates 
  public F_q Qa_x = F_q("10718403022999374947945725276380051801202505726612245009114259428117304302096"); 
  public F_q Qa_y = F_q("11185298449603894178049648458003171075534367363442926049311673535798468787055"); 
   
  // Message 
  public F_l e; 
  // r component of ECDSA signature 
  public F_l r; 
  // s component of ECDSA signature 
  public F_l s; 
   
  // baby_jubjub a & d parameters 
  public F_q a = F_q("168700"); 
  public F_q d = F_q("168696"); 
   
  inputs { 
    e, r, s 
  } 
  outputs { 
    << ... >>  
  } 
  witnesses_AssertRange { 
    << ... >>  
  } 
  witnesses { 
    << ... >>  
  } 
   
  public void outsource() { 
    F_l w = s.inv; 
    F_l u1 = e * w; 
    F_l u2 = r * w; 
    F_q[] Pa = scalarMult(u1, b_x, b_y); 
    F_q[] Pb = scalarMult(u2, Qa_x, Qa_y); 
    F_q[] P = addPoints(Pa[0], Pa[1], Pb[0], Pb[1]); 
    uint_256 l = uint_256("2736030358979909402780800718157159386076813972158567259200215660948447373041"); 
    uint_256 res = underlyingQ(P[0]) % l; 
    verifyEq ( res , underlyingL(r) ); 
  } 
   
  private uint_256 underlyingQ(F_q elem) { 
    uint_256 base = 2; 
    uint_256 acc = 1; 
    uint_256 res = 0; 
     
    for (int i = 0; i < elem.bits.length; i++) { 
      if (elem.bits[i]) { 
        res = res + acc; 
      } 
      acc = base * acc; 
    } 
     
    return res; 
  } 
   
  private uint_256 underlyingL(F_l elem) { 
    uint_256 base = 2; 
    uint_256 acc = 1; 
    uint_256 res = 0; 
     
    for (int i = 0; i < elem.bits.length; i++) { 
      if (elem.bits[i]) { 
        res = res + acc; 
      } 
      acc = base * acc; 
    } 
     
    return res; 
  } 
   
  private F_q[] scalarMult(F_q d, F_q x1, F_q y1) { 
    F_q q_x = F_q(0); 
    F_q q_y = F_q(1); 
    F_q r_x = x1; 
    F_q r_y = y1; 
     
    for (int i = 0; i < d.bits.length; i++) { 
      if (d.bits[i]) { 
        F_q[] Q = addPoints(q_x, q_y, r_x, r_y); 
        q_x = Q[0]; 
        q_y = Q[1]; 
      } 
      F_q[] R = doublePoint(r_x, r_y); 
      r_x = R[0]; 
      r_y = R[1]; 
    } 
     
    return new F_q[]{q_x, q_y}; 
  } 
   
   
  private F_q[] addPoints(F_q x1, F_q y1, F_q x2, F_q y2) { 
    F_q x3 = (x1 * y2 + y1 * x2) / (F_q(1) + d * x1 * x2 * y1 * y2); 
    F_q y3 = (y1 * y2 - a * x1 * x2) / (F_q(1) - d * x1 * x2 * y1 * y2); 
    return new F_q[]{x3, y3}; 
  } 
   
  private F_q[] doublePoint(F_q x1, F_q y1) { 
    return addPoints(x1, y1, x1, y1); 
  } 
   
  SampleRun("Sample_Run1", true){ 
    pre { 
        e.val = new BigInteger("12323112"); 
        r.val = new BigInteger("98730040599697266141788813371553793591114429373120916256144787699762701182"); 
        s.val = new BigInteger("1651849609606016295673287613426629540326019090116590931600124077358593797031"); 
    } 
    post { 
        <no statements> 
    } 
  } 
   
   
   
  public static void main(string[] args) { 
    // This is the java main method. Its purpose is to make the Progam runnable in the environment 
    // This method can be left empty, or used to set Configuration params (see examples) 
    Config.hexOutputEnabled = false; 
  } 
}
```

This variant of the program works as expected. However, if I don't use constants for specifying the public key coordinates `Qa_x` and `Qa_y`, but instead require those to be witnesses, it breaks:
```java
Program ECDSA_Verification { 
 
  //  ECDSA verification using baby_jub_jub curve 
   
  // Generator point 
  public F_q b_x = F_q("17777552123799933955779906779655732241715742912184938656739573121738514868268"); 
  public F_q b_y = F_q("2626589144620713026669568689430873010625803728049924121243784502389097019475"); 
   
  // Public key coordinates 
  public F_q Qa_x; 
  public F_q Qa_y; 
   
  // Message 
  public F_l e; 
  // r component of ECDSA signature 
  public F_l r; 
  // s component of ECDSA signature 
  public F_l s; 
   
  // baby_jubjub a & d parameters 
  public F_q a = F_q("168700"); 
  public F_q d = F_q("168696"); 
   
  inputs { 
    e, r, s 
  } 
  outputs { 
    << ... >>  
  } 
  witnesses_AssertRange { 
    << ... >>  
  } 
  witnesses { 
    Qa_x, Qa_y  
  } 
   
  public void outsource() { 
    F_l w = s.inv; 
    F_l u1 = e * w; 
    F_l u2 = r * w; 
    F_q[] Pa = scalarMult(u1, b_x, b_y); 
    F_q[] Pb = scalarMult(u2, Qa_x, Qa_y); 
    F_q[] P = addPoints(Pa[0], Pa[1], Pb[0], Pb[1]); 
    uint_256 l = uint_256("2736030358979909402780800718157159386076813972158567259200215660948447373041"); 
    verifyEq ( underlyingQ(P[0]) % l , underlyingL(r) ); 
  } 
   
  private uint_256 underlyingQ(F_q elem) { 
    uint_256 base = 2; 
    uint_256 acc = 1; 
    uint_256 res = 0; 
     
    for (int i = 0; i < elem.bits.length; i++) { 
      if (elem.bits[i]) { 
        res = res + acc; 
      } 
      acc = base * acc; 
    } 
     
    return res; 
  } 
   
  private uint_256 underlyingL(F_l elem) { 
    uint_256 base = 2; 
    uint_256 acc = 1; 
    uint_256 res = 0; 
     
    for (int i = 0; i < elem.bits.length; i++) { 
      if (elem.bits[i]) { 
        res = res + acc; 
      } 
      acc = base * acc; 
    } 
     
    return res; 
  } 
   
  private F_q[] scalarMult(F_q d, F_q x1, F_q y1) { 
    F_q q_x = F_q(0); 
    F_q q_y = F_q(1); 
    F_q r_x = x1; 
    F_q r_y = y1; 
     
    for (int i = 0; i < d.bits.length; i++) { 
      if (d.bits[i]) { 
        F_q[] Q = addPoints(q_x, q_y, r_x, r_y); 
        q_x = Q[0]; 
        q_y = Q[1]; 
      } 
      F_q[] R = doublePoint(r_x, r_y); 
      r_x = R[0]; 
      r_y = R[1]; 
    } 
     
    return new F_q[]{q_x, q_y}; 
  } 
   
   
  private F_q[] addPoints(F_q x1, F_q y1, F_q x2, F_q y2) { 
    F_q x3 = (x1 * y2 + y1 * x2) / (F_q(1) + d * x1 * x2 * y1 * y2); 
    F_q y3 = (y1 * y2 - a * x1 * x2) / (F_q(1) - d * x1 * x2 * y1 * y2); 
    return new F_q[]{x3, y3}; 
  } 
   
  private F_q[] doublePoint(F_q x1, F_q y1) { 
    return addPoints(x1, y1, x1, y1); 
  } 
   
  SampleRun("Sample_Run1", true){ 
    pre { 
        e.val = new BigInteger("12323112"); 
        r.val = new BigInteger("98730040599697266141788813371553793591114429373120916256144787699762701182"); 
        s.val = new BigInteger("1651849609606016295673287613426629540326019090116590931600124077358593797031"); 
         
        Qa_x.val = new BigInteger("10718403022999374947945725276380051801202505726612245009114259428117304302096"); 
        Qa_y.val = new BigInteger("11185298449603894178049648458003171075534367363442926049311673535798468787055"); 
    } 
    post { 
        <no statements> 
    } 
  } 
   
   
   
  public static void main(string[] args) { 
    // This is the java main method. Its purpose is to make the Progam runnable in the environment 
    // This method can be left empty, or used to set Configuration params (see examples) 
    Config.hexOutputEnabled = false; 
  } 
}
```
with the following error:
```
887105075*1!=213099390
Error - Assertion Failed assert in 2 <54961 0> out 1 <61386> 		# Equality assertion of long elements | case 2 | index 0
Exception in thread "main" java.lang.RuntimeException: Error During Circuit Evaluation
	at backend.operations.primitive.AssertBasicOp.compute(AssertBasicOp.java:29)
	at backend.operations.primitive.BasicOp.evaluate(BasicOp.java:63)
	at backend.eval.CircuitEvaluator.evaluate(CircuitEvaluator.java:154)
	at backend.structure.CircuitGenerator.__evaluateSampleRun(CircuitGenerator.java:452)
	at xjsnark.ecdsa.ECDSA_Verification.<init>(ECDSA_Verification.java:29)
	at xjsnark.ecdsa.ECDSA_Verification.main(ECDSA_Verification.java:23)

Process finished with exit code 1
```

Am I doing something wrong in the above?

**Comment by akosba** [comment]
- For me to help with debugging this, could you send me the model file? (.mps)
- This is an independent question, do you intend to use the above program over the default field used in xJsnark? It's likely going to be an expensive circuit this way. You can change the native field to q itself, if you have a suitable zksnark back end. The instructions are in the xJsnark readme. (To see what I mean, check this old article about JubJub: https://z.cash/technology/jubjub/  These performance numbers are only valid if the native field matches the base field of the curve. The same could apply in your case )

**Comment by sanchopansa** [comment]
Thank you for taking the time to look into this! Attached is the MPS file (working version, where `Qa_x` and `Qa_y` are constants).

Regarding your second question: thank you for bringing this inefficiency up. I am aware that because the native field of xJsnark is the one for BN-128, I will run into this problem. I looked at the `EC_KeyKnowledge` example and I noticed that there a similar problem exists (iiuc), but I saw we end up with about 600-700K constraints, so if I end up with a similar number for this program, I would be happy for now. In the end, what I would like to do (if feasible) is ECDSA signature verification for `secp256k1` and I'm not sure a SNARK back end is available for this curve (or if one is even theoretically possible because of the pairing operations).

One question, though: my understanding is that jsnark relies on libsnark as a backend. So, if I were to change the backend, I would be limited to the curves supported in libsnark, right? Or is there some easier way to integrate with other backends?

[ecdsa.mps.zip](https://github.com/akosba/xjsnark/files/2691914/ecdsa.mps.zip)

**Comment by sanchopansa** [comment]
I just realized I was being stupid yesterday: the baby_jubjub curve, which the above implementation is using is not the JubJub curve used in Zcash. baby_jubjub is to BN-128 what JubJub is to BLS12-381, so doing those computations over baby_jubjub should be efficient using the default backend in xjsnark.

However, for what I'm actually trying to do (ECDSA over secp256k1), it will most likely result in an expensive circuit, as you mentioned, but I would like to see the exact numbers to figure out if it is feasible or not.

**Comment by akosba** [comment]
- There was an issue in how sample runs assign values to native field types. I just pushed a fix.
- I also fixed one of the type checks that will lead to an error in your code. Basically, you will need to change:
`private F_q[] scalarMult(F_q d, F_q x1, F_q y1) {`
to
`private F_q[] scalarMult(F_l d, F_q x1, F_q y1) {`

>  the baby_jubjub curve, which the above implementation is using is not the JubJub curve used in Zcash. baby_jubjub is to BN-128 what JubJub is to BLS12-381, so doing those computations over baby_jubjub should be efficient using the default backend in xjsnark.

I see. I also did not notice that the q in your FieldDefTable matches the base field for BN-128. In that case, it will be ok.

**Comment by sanchopansa** [comment]
Thank you for fixing this and for catching the type mismatch in the code. I can confirm that the fix is working.

When I switched to secp256k1, I once again got an exception, but I'm still trying to figure out if this is something that I messed up in the implementation. I would keep this issue open while I debug this, if you don't mind.
