### ISSUE TITLE
StackOverflow exception when building circuit

### ISSUE THREAD

**Issue by sanchopansa** [akosba/xjsnark#11]
I wrote some code to experiment with ECDSA verification over secp256k1. I realize this is going to be an expensive circuit, as we discussed, but I would like to quantify exactly how expensive. However, I'm running into a `StackOverflow` exception when building the circuit (as far as I can tell):

```
[1st Phase] Running Initial Circuit Analysis for < ECDSA_Verification_secp256k1 >
Exception in thread "main" java.lang.StackOverflowError
	at backend.auxTypes.PackedValue.getConstant(PackedValue.java:660)
	at backend.auxTypes.FieldElement.checkConstant(FieldElement.java:598)
	at backend.auxTypes.FieldElement.init(FieldElement.java:392)
	at backend.auxTypes.FieldElement.<init>(FieldElement.java:304)
	at backend.auxTypes.FieldElement.<init>(FieldElement.java:328)
	at backend.auxTypes.FieldElement.<init>(FieldElement.java:333)
	at backend.auxTypes.FieldElement.negate(FieldElement.java:930)
	at backend.auxTypes.FieldElement.subtract(FieldElement.java:865)
	at backend.auxTypes.FieldElement.negate(FieldElement.java:930)
	at backend.auxTypes.FieldElement.subtract(FieldElement.java:865)
	at backend.auxTypes.FieldElement.negate(FieldElement.java:930)
	at backend.auxTypes.FieldElement.subtract(FieldElement.java:865)
	at backend.auxTypes.FieldElement.negate(FieldElement.java:930)
...
```

Am I completely out of luck here because the circuit is truly humongous or is it possible to get it to build by tweaking some parameters?

P.S. I am aware some optimizations are possible (e.g. using the Jacobian coordinates), but for now I want to see if it's feasible to get somewhere with the current approach.

[ecdsa.mps.zip](https://github.com/akosba/xjsnark/files/2706263/ecdsa.mps.zip)

**Comment by sanchopansa** [comment]
Here are the contents of the `FieldDefTable`:
```
Field Mappings:                                                                             
q : 21888242871839275222246405745257275088548364400416034343698204186575808495617           
swifft : 257                                                                                
l : 2736030358979909402780800718157159386076813972158567259200215660948447373041            
secp256k1_n : 115792089237316195423570985008687907853269984665640564039457584007908834671663
secp256k1_l : 115792089237316195423570985008687907852837564279074904382605163141518161494337
```

**Comment by akosba** [comment]
I looked at your code. Here are some comments:
- I was not able to verify that the public key was properly generated unless I am missing something, i.e.,  pk.y^2 was not equal to pk.x^3 + 7 (mod the base field)
- I think the scalar multiplication method in your implementation has to account for the special case of the first addition. (adding the initial q_x, q_y won't lead to correct results here)
- You can now use the new Field to Field conversion function to make things more straightforward in the last step of your implementation, e.g., you could do:

`verifyEq ( F_secp256k1_l(P[0]) , r ); `

instead of 

```
uint_256 l = uint_256("115792089237316195423570985008687907852837564279074904382605163141518161494337"); 
uint_256 res = underlyingQ(P[0]) % l; 
verifyEq ( res , underlyingL(r) ); 
```

Below, you can find a modified version of your code that I tested with a couple of cases and worked (please make sure to update to the most recent version, as I fixed something in the new field to field conversion functions). If you face other issues, let me know.

```
Program ECDSA_Verification_secp256k1 { 
 
  //  ECDSA verification using secp256k1 curve 
   
  // Generator point 
  public F_secp256k1_n g_x = F_secp256k1_n("55066263022277343669578718895168534326250603453777594175500187360389116729240"); 
  public F_secp256k1_n g_y = F_secp256k1_n("32670510020758816978083085130507043184471273380659243275938904335757337482424"); 
   
  // Public key coordinates 
  public F_secp256k1_n pk_x; 
  public F_secp256k1_n pk_y; 
   
  // Message 
  public F_secp256k1_l e; 
  // r component of ECDSA signature 
  public F_secp256k1_l r; 
  // s component of ECDSA signature 
  public F_secp256k1_l s; 
   
  // secp256k1 b parameter (a is 0) 
  public F_secp256k1_n b = F_secp256k1_n(7); 
   
  inputs { 
    e, r, s 
  } 
  outputs { 
    << ... >>  
  } 
  witnesses_AssertRange { 
    << ... >>  
  } 
  witnesses { 
    pk_x, pk_y  
  } 
   
  public void outsource() { 
    F_secp256k1_l w = s.inv; 
    F_secp256k1_l u1 = e * w; 
    F_secp256k1_l u2 = r * w; 
    F_secp256k1_n[] Pa = scalarMult(u1, g_x, g_y); 
    F_secp256k1_n[] Pb = scalarMult(u2, pk_x, pk_y); 
    F_secp256k1_n[] P = addPoints(Pa[0], Pa[1], Pb[0], Pb[1]); 
     
     
    verifyEq ( F_secp256k1_l(P[0]) , r ); 
    // uint_256 l = uint_256("115792089237316195423570985008687907852837564279074904382605163141518161494337"); 
    // uint_256 res = underlyingQ(P[0]) % l; 
    // verifyEq ( res , underlyingL(r) ); 
    //  
     
     
  } 
      
  private F_secp256k1_n[] scalarMult(F_secp256k1_l d, F_secp256k1_n x1, F_secp256k1_n y1) { 
    F_secp256k1_n q_x = F_secp256k1_n(0); 
    F_secp256k1_n q_y = F_secp256k1_n(1); 
    F_secp256k1_n r_x = x1; 
    F_secp256k1_n r_y = y1; 
    bit init = bit(false); 
    for (int i = 0; i < d.bits.length; i++) { 
      if (d.bits[i]) { 
        if (init) { 
          F_secp256k1_n[] Q = addPoints(q_x, q_y, r_x, r_y); 
          q_x = Q[0]; 
          q_y = Q[1]; 
        } else { 
          init = bit(true); 
          q_x = r_x; 
          q_y = r_y; 
        } 
      } 
      F_secp256k1_n[] R = doublePoint(r_x, r_y); 
      r_x = R[0]; 
      r_y = R[1]; 
    } 
     
    return new F_secp256k1_n[]{q_x, q_y}; 
  } 
   
  private F_secp256k1_n[] addPoints(F_secp256k1_n x1, F_secp256k1_n y1, F_secp256k1_n x2, F_secp256k1_n y2) { 
    F_secp256k1_n lambda = (y2 - y1) / (x2 - x1); 
    F_secp256k1_n xr = lambda * lambda - x1 - x2; 
    F_secp256k1_n yr = lambda * (x1 - xr) - y1; 
    return new F_secp256k1_n[]{xr, yr}; 
  } 
   
  private F_secp256k1_n[] doublePoint(F_secp256k1_n x1, F_secp256k1_n y1) { 
    F_secp256k1_n lambda = (F_secp256k1_n(3) * x1 * x1) / (F_secp256k1_n(2) * y1); 
    F_secp256k1_n xr = lambda * lambda - x1 * F_secp256k1_n(2); 
    F_secp256k1_n yr = lambda * (x1 - xr) - y1; 
     
    return new F_secp256k1_n[]{xr, yr}; 
  } 
   
  SampleRun("Sample_Run1", true){ 
    pre { 
        e.val = new BigInteger("891878777181617615151551444414141414141331"); 
        r.val = new BigInteger("114952186484025444352584917022504898685808581054355936573231700616108892076242"); 
        s.val = new BigInteger("53728427064049904465957456845741248417514844054141805720119159855410599300247"); 
         
        pk_x.val = new BigInteger("106632837055762129491782811468324055646881304543031595536739959834385597839421"); 
        pk_y.val = new BigInteger("29770903370365777878065655902671341533828950995404829172207720614707648631045"); 
    } 
    post { 
        <no statements> 
    } 
  } 
   
   
   
  public static void main(string[] args) { 
    // This is the java main method. Its purpose is to make the Progam runnable in the environment 
    // This method can be left empty, or used to set Configuration params (see examples) 
    Config.hexOutputEnabled = false; 
  } 
}
```

By the way, if the signature and other values are provided as witnesses, the assert range witness block should be used, to make sure that the prover inputs valid values in range.

**Comment by sanchopansa** [comment]
@akosba -- thank you very much for your help! My apologies for the slow answer, but with the festive period now, I'm afk for most of the time.

I was not using the latest version of the code, so that would have been the reason why I got the `StackOverflow` exception I guess.

> I was not able to verify that the public key was properly generated unless I am missing something, i.e., pk.y^2 was not equal to pk.x^3 + 7 (mod the base field)
Indeed, that's a bit embarrassing... I have copied the wrong values from my Python interpreter.

> You can now use the new Field to Field conversion function to make things more straightforward in the last step of your implementation, e.g., you could do:
That's super awesome and thank you for implementing it so quickly. I hadn't realized that it's already in. I really want to stress that the expressiveness of the DSL is very impressive, in particular the capability to mix different fields and use unsigned ints in the same program. Now with the built-in conversions, it's even better!

> By the way, if the signature and other values are provided as witnesses, the assert range witness block should be used, to make sure that the prover inputs valid values in range.
I have now done this as well, thank you!
