### ISSUE TITLE
IndexOutOfBounds exception when printing bit decomposition 

### ISSUE THREAD

**Issue by sanchopansa** [akosba/xjsnark#8]
I think I might have hit some problem with the bit representation of field elements (as in the bit representation is not what I expect it to be). I started debugging this, but I got the following error along the way:
```
/usr/lib/jvm/java-8-openjdk-amd64/bin/java -classpath /home/sancho/software/mps/MPS 3.3/languages/baseLanguage/jetbrains.mps.baseLanguage.tuples.jar:/home/sancho/software/mps/MPS 3.3/languages/baseLanguage/jetbrains.mps.baseLanguage.blTypes.jar:/home/sancho/software/mps/MPS 3.3/languages/languageDesign/jetbrains.mps.lang.scopes.runtime.jar:/home/sancho/software/mps/MPS 3.3/languages/baseLanguage/jetbrains.mps.baseLanguage.jdk7.jar:/home/sancho/software/mps/MPS 3.3/lib/jdom.jar:/home/sancho/src/mps-projects/xjsnark/languages/xjsnark/runtime/classes_gen:/home/sancho/software/mps/MPS 3.3/languages/languageDesign/jetbrains.mps.lang.scopes.jar:/home/sancho/software/mps/MPS 3.3/languages/languageDesign/jetbrains.mps.lang.resources.jar:/home/sancho/software/mps/MPS 3.3/languages/languageDesign/jetbrains.mps.lang.smodel.jar:/home/sancho/software/mps/MPS 3.3/lib/sanselan-0.98-snapshot.jar:/home/sancho/software/mps/MPS 3.3/languages/languageDesign/jetbrains.mps.lang.generator.jar:/home/sancho/software/mps/MPS 3.3/languages/languageDesign/jetbrains.mps.lang.intentions.jar:/home/sancho/software/mps/MPS 3.3/languages/languageDesign/jetbrains.mps.lang.project.jar:/home/sancho/software/mps/MPS 3.3/languages/languageDesign/jetbrains.mps.lang.checkedName.jar:/home/sancho/software/mps/MPS 3.3/lib/mps-editor-runtime.jar:/home/sancho/software/mps/MPS 3.3/lib/xstream-1.4.3.jar:/home/sancho/src/mps-projects/xjsnark/languages/xjsnark/sandbox/classes_gen:/home/sancho/software/mps/MPS 3.3/languages/languageDesign/jetbrains.mps.lang.sharedConcepts.jar:/home/sancho/software/mps/MPS 3.3/languages/baseLanguage/jetbrains.mps.baseLanguage.javadoc.jar:/home/sancho/software/mps/MPS 3.3/lib/forms_rt.jar:/home/sancho/software/mps/MPS 3.3/lib/mps-icons.jar:/home/sancho/software/mps/MPS 3.3/lib/mps-editor-api.jar:/home/sancho/software/mps/MPS 3.3/lib/asm-all.jar:/home/sancho/software/mps/MPS 3.3/lib/annotations.jar:/home/sancho/src/mps-projects/xjsnark/languages/xjsnark/classes_gen:/home/sancho/software/mps/MPS 3.3/languages/languageDesign/jetbrains.mps.lang.pattern.jar:/home/sancho/software/mps/MPS 3.3/lib/mps-collections.jar:/home/sancho/software/mps/MPS 3.3/lib/platform.jar:/home/sancho/software/mps/MPS 3.3/languages/languageDesign/jetbrains.mps.baseLanguage.lightweightdsl.jar:/home/sancho/software/mps/MPS 3.3/languages/languageDesign/jetbrains.mps.lang.textGen.jar:/home/sancho/software/mps/MPS 3.3/lib/extensions.jar:/home/sancho/software/mps/MPS 3.3/languages/languageDesign/jetbrains.mps.lang.typesystem.jar:/home/sancho/software/mps/MPS 3.3/languages/baseLanguage/jetbrains.mps.baseLanguage.regexp.runtime.jar:/home/sancho/software/mps/MPS 3.3/languages/languageDesign/jetbrains.mps.lang.refactoring.jar:/home/sancho/software/mps/MPS 3.3/languages/baseLanguage/jetbrains.mps.baseLanguage.closures.jar:/home/sancho/software/mps/MPS 3.3/languages/languageDesign/jetbrains.mps.lang.quotation.jar:/home/sancho/software/mps/MPS 3.3/lib/ecj-4.4.jar:/home/sancho/software/mps/MPS 3.3/lib/trove4j.jar:/home/sancho/software/mps/MPS 3.3/lib/platform-api.jar:/home/sancho/software/mps/MPS 3.3/languages/baseLanguage/jetbrains.mps.baseLanguage.collections.jar:/home/sancho/software/mps/MPS 3.3/lib/mps-tuples.jar:/home/sancho/software/mps/MPS 3.3/languages/languageDesign/jetbrains.mps.lang.actions.jar:/home/sancho/software/mps/MPS 3.3/languages/baseLanguage/jetbrains.mps.baseLanguageInternal.jar:/home/sancho/software/mps/MPS 3.3/lib/mps-platform.jar:/home/sancho/software/mps/MPS 3.3/languages/languageDesign/jetbrains.mps.lang.generator.generationContext.jar:/home/sancho/software/mps/MPS 3.3/lib/guava-17.0.jar:/home/sancho/software/mps/MPS 3.3/lib/diffutils-1.2.1.jar:/home/sancho/software/mps/MPS 3.3/languages/languageDesign/jetbrains.mps.lang.behavior.jar:/home/sancho/software/mps/MPS 3.3/languages/baseLanguage/jetbrains.mps.baseLanguage.extensionMethods.jar:/home/sancho/software/mps/MPS 3.3/languages/languageDesign/jetbrains.mps.lang.core.jar:/home/sancho/software/mps/MPS 3.3/lib/util.jar:/home/sancho/software/mps/MPS 3.3/languages/languageDesign/jetbrains.mps.lang.traceable.jar:/home/sancho/software/mps/MPS 3.3/lib/mps-behavior-runtime.jar:/home/sancho/software/mps/MPS 3.3/lib/mps-openapi.jar:/home/sancho/software/mps/MPS 3.3/languages/languageDesign/jetbrains.mps.lang.migration.jar:/home/sancho/software/mps/MPS 3.3/languages/baseLanguage/jetbrains.mps.baseLanguage.scopes.jar:/home/sancho/software/mps/MPS 3.3/languages/languageDesign/jetbrains.mps.lang.migration.runtime.jar:/home/sancho/src/mps-projects/xjsnark/languages/xjsnark/runtime/lib/xjsnark_backend.jar:/home/sancho/software/mps/MPS 3.3/languages/baseLanguage/jetbrains.mps.baseLanguage.jar:/home/sancho/software/mps/MPS 3.3/languages/languageDesign/jetbrains.mps.lang.constraints.jar:/home/sancho/software/mps/MPS 3.3/lib/mps-behavior-api.jar:/home/sancho/software/mps/MPS 3.3/languages/baseLanguage/jetbrains.mps.baseLanguage.classifiers.jar:/home/sancho/software/mps/MPS 3.3/lib/mps-editor.jar:/home/sancho/software/mps/MPS 3.3/languages/languageDesign/jetbrains.mps.lang.structure.jar:/home/sancho/software/mps/MPS 3.3/languages/languageDesign/jetbrains.mps.lang.script.jar:/home/sancho/software/mps/MPS 3.3/lib/log4j.jar:/home/sancho/software/mps/MPS 3.3/languages/languageDesign/jetbrains.mps.lang.smodel.query.jar:/home/sancho/software/mps/MPS 3.3/languages/baseLanguage/jetbrains.mps.baseLanguage.logging.jar:/home/sancho/software/mps/MPS 3.3/lib/picocontainer.jar:/home/sancho/software/mps/MPS 3.3/languages/languageDesign/jetbrains.mps.lang.editor.jar:/home/sancho/software/mps/MPS 3.3/lib/mps-core.jar:/home/sancho/software/mps/MPS 3.3/languages/baseLanguage/jetbrains.mps.baseLanguage.logging.runtime.jar:/home/sancho/software/mps/MPS 3.3/lib/mps-closures.jar:/home/sancho/software/mps/MPS 3.3/languages/languageDesign/jetbrains.mps.lang.plugin.jar xjsnark.BitDecomposition.BitDecompositionTest
[1st Phase] Running Initial Circuit Analysis for < BitDecompositionTest >
Phase 1: Analysis Completed!
[2nd Phase] Running Circuit Generator for < BitDecompositionTest >
Circuit Generation Done for < BitDecompositionTest >  
 	 Total Number of Constraints :  0

Running Sample Run: Sample_Run1
Exception in thread "main" java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:657)
	at java.util.ArrayList.get(ArrayList.java:433)
	at backend.structure.CircuitGenerator.__checkConstantState(CircuitGenerator.java:786)
	at xjsnark.BitDecomposition.BitDecompositionTest$1.pre(BitDecompositionTest.java:34)
	at backend.structure.CircuitGenerator.__evaluateSampleRun(CircuitGenerator.java:449)
	at xjsnark.BitDecomposition.BitDecompositionTest.<init>(BitDecompositionTest.java:28)
	at xjsnark.BitDecomposition.BitDecompositionTest.main(BitDecompositionTest.java:22)

Process finished with exit code 1
```

The above happens for a program which only has content in the `pre` block. The code is the following (`l` is `2736030358979909402780800718157159386076813972158567259200215660948447373041`):
```java
SampleRun("Sample_Run1", true){ 
  pre { 
      F_l x = F_l("127"); 
      for (int i = 0; i < x.bits.length; i++) { 
        if (x.bits[i]) { 
          System.out.println("1"); 
        } else { 
          System.out.println("0"); 
        } 
      } 
  } 
  post { 
      <no statements> 
  } 
}
```
Am I doing something wrong in the above or could it be a bug?

**Comment by akosba** [comment]
This code 
 ```
     F_l x = F_l("127"); 
      for (int i = 0; i < x.bits.length; i++) { 
        if (x.bits[i]) { 
          System.out.println("1"); 
        } else { 
          System.out.println("0"); 
        } 
      }
```
should not be written inside a pre block. The pre and post blocks should not implement circuit logic or instantiate new xjsnark variables. The pre block is only intended for assigning values to certain variables in the very beginning (as a sample test), and the post block is intended to check values on other variables after running the circuit with the values set in the pre block.

For debugging, I have internal instructions for debugging but I have not added front end support for them yet, but meanwhile here is a trick you could use using the current version (note that local variables will need to be (effectively) final in order to be accessed in external blocks):
```
public void outsource() { 
  uint_256 modulus = x * y; 
  f = z % modulus; 
  final bit[] bits = f.bits; 
  external { 
      for (int i = 0; i < bits.length; i++) { 
        System.out.println("value @ bit " + i + " is " + bits[i].val); 
      } 
  } 
}
```

**Comment by sanchopansa** [comment]
I understand, thank you for the clarification. I'll resort to the external block for debugging for now.
