### ISSUE TITLE
Bug in verifyEq for values >= 2 ^ 32?

### ISSUE THREAD

**Issue by sanchopansa** [akosba/xjsnark#9]
I have the following program (with `l=2736030358979909402780800718157159386076813972158567259200215660948447373041`):
```java
Program VerifyEqTest { 
 
  public F_l fieldElement; 
  public uint_256 underlyingValue; 
   
  inputs { 
    << ... >> 
  } 
  outputs { 
    fieldElement, underlyingValue  
  } 
  witnesses_AssertRange { 
    << ... >>  
  } 
  witnesses { 
    << ... >>  
  } 
   
   
  public void outsource() { 
    fieldElement = F_l("4294967295"); 
    underlyingValue = uint_256("4294967295"); 
     
    verifyEq ( underlying(fieldElement) , underlyingValue ); 
  } 
   
  private uint_256 underlying(F_l elem) { 
    uint_256 base = 2; 
    uint_256 acc = 1; 
    uint_256 res = 0; 
     
    for (int i = 0; i < elem.bits.length; i++) { 
      if (elem.bits[i]) { 
        res = res + acc; 
      } 
      acc = base * acc; 
    } 
     
    return res; 
  } 
   
  SampleRun("Sample_Run1", true){ 
    pre { 
        <no statements> 
    } 
    post { 
        <no statements> 
    } 
  } 
   
   
  public static void main(string[] args) { 
    // This is the java main method. Its purpose is to make the Progam runnable in the environment 
    // This method can be left empty, or used to set Configuration params (see examples) 
    Config.hexOutputEnabled = false; 
  } 
}
```

When running it with `4294967295` (2 ^ 32 - 1) as above, the verification check is successful. However, running it with `4294967296` (2 ^ 32), it fails:
```
[1st Phase] Running Initial Circuit Analysis for < VerifyEqTest >
Phase 1: Analysis Completed!
[2nd Phase] Running Circuit Generator for < VerifyEqTest >
Exception in thread "main" java.lang.RuntimeException: Constraint fails on constant uints
	at backend.auxTypes.UnsignedInteger.forceEqual(UnsignedInteger.java:1733)
	at xjsnark.BitDecomposition.VerifyEqTest.outsource(VerifyEqTest.java:104)
	at backend.structure.CircuitGenerator.__phase2(CircuitGenerator.java:182)
	at backend.structure.CircuitGenerator.__generateCircuit(CircuitGenerator.java:140)
	at xjsnark.BitDecomposition.VerifyEqTest.<init>(VerifyEqTest.java:28)
	at xjsnark.BitDecomposition.VerifyEqTest.main(VerifyEqTest.java:23)

Process finished with exit code 1
```

Do you have an idea why this is the case?

**Comment by sanchopansa** [comment]
The fix appears to be working :+1:

**Comment by akosba** [comment]
Thanks for noticing this. The issue was in the bits operator when operating on long constants. Padding was incorrectly applied for constant chunks. I also added a similar fix [here](https://github.com/akosba/jsnark/commit/595228637ab38529f0782f40a2fb26f79d88ab0f).
